"use client";

import { AnimatePresence, motion } from "motion/react";
import { cn } from "@/lib/utils";
import type { PlayerProps } from "./types";

export function RepetitionPlayer({
  exercise,
  config,
  timer,
  personalizedItems = [],
}: PlayerProps) {
  const isSyllablePractice = exercise.title
    .toLowerCase()
    .includes("syllable");

  /*
   * PERSONALIZED PRACTICE
   * ---------------------
   * Word Repetition:
   *   personalizedItems contains target words from
   *   the previous speech analysis.
   *
   * Syllable Practice:
   *   personalizedItems will contain syllable items
   *   generated by the backend personalization service.
   *
   * No frontend syllable guessing is performed here.
   */
  const personalized = personalizedItems
    .map((item) => item.trim())
    .filter(Boolean);

  /*
   * If personalized content is available, use it.
   * Otherwise fall back to the exercise's original
   * static catalogue.
   */
  const items =
    personalized.length > 0
      ? personalized
      : (exercise.content?.items ?? []);

  if (items.length === 0) return null;

  const itemSeconds = config.itemSeconds ?? 6;
  const reps = Math.max(1, config.reps ?? 3);
  const beatSeconds = itemSeconds / reps;

  const idle = !timer.running && timer.elapsed === 0;

  const itemIndex =
    Math.floor(timer.elapsed / itemSeconds) % items.length;

  const timeInItem = timer.elapsed % itemSeconds;

  const beat = Math.min(
    reps - 1,
    Math.floor(timeInItem / beatSeconds),
  );

  const beatProgress =
    (timeInItem % beatSeconds) / beatSeconds;

  const current = idle ? items[0] : items[itemIndex];

  return (
    <div className="space-y-6">
      {personalized.length > 0 ? (
        <div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-center">
          <p className="text-xs font-medium uppercase tracking-wide text-primary">
            Personalized practice
          </p>

          <p className="mt-1 text-xs text-muted-foreground">
            {isSyllablePractice
              ? "Syllables generated from your previous speech analysis"
              : "Based on words from your previous speech analysis"}
          </p>
        </div>
      ) : null}

      <div className="relative grid min-h-56 place-items-center overflow-hidden rounded-2xl border bg-linear-to-br from-primary/10 to-transparent p-8">
        <AnimatePresence mode="wait">
          <motion.p
            key={`${current}-${idle}`}
            initial={{ opacity: 0, scale: 0.92 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 1.06 }}
            transition={{ duration: 0.2 }}
            className="text-center text-5xl font-semibold tracking-tight sm:text-6xl"
          >
            {current}
          </motion.p>
        </AnimatePresence>

        {/* Beat pulse: one dot lights up per repetition. */}
        <div className="absolute bottom-6 flex gap-2">
          {Array.from({ length: reps }, (_, i) => (
            <motion.span
              key={i}
              className={cn(
                "size-2.5 rounded-full",
                !idle && i === beat
                  ? "bg-primary"
                  : "bg-primary/25",
              )}
              animate={
                !idle && i === beat
                  ? {
                      scale:
                        1 + (1 - beatProgress) * 0.6,
                    }
                  : { scale: 1 }
              }
              transition={{
                duration: 0.12,
                ease: "linear",
              }}
            />
          ))}
        </div>
      </div>

      <p className="text-center text-sm text-muted-foreground">
        {idle
          ? isSyllablePractice
            ? `Say each syllable ${reps} times, slowly.`
            : `Say each word ${reps} times, slowly.`
          : `Repetition ${beat + 1} of ${reps} · item ${
              itemIndex + 1
            } of ${items.length}`}
      </p>

      <div className="flex flex-wrap justify-center gap-2">
        {items.map((item, i) => (
          <span
            key={`${item}-${i}`}
            className={cn(
              "rounded-full px-3 py-1 text-xs font-medium transition-colors",
              !idle && i === itemIndex
                ? "bg-primary text-primary-foreground"
                : "bg-muted text-muted-foreground",
            )}
          >
            {item}
          </span>
        ))}
      </div>
    </div>
  );
}